baseURL = 'https://himanhsugusain.github.io/'
locale = 'en-us'
title = 'Systems, Software and Slowbot'
theme = 'hugo-theme'
publishDir = 'docs'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
