baseURL = 'https://himanhsugusain.github.io/'
languageCode = 'en-us'
title = 'Slowbot Writes'
theme = ['mini']

[pagination]
pagerSize = 3

[params.social]
github = 'https://github.com/himanhsugusain'
linkedin = 'https://www.linkedin.com/in/himanshugusain'

[params]
author = 'Himanshu Gusain'
bio = 'Software Engineer, Site Reliablity'
description = 'Things I know or atleast I think so'
