baseURL = 'https://himanhsugusain.github.io/'
locale = 'en-us'
title = 'Slowbot Systems and Software'
theme = 'hugo-theme'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
